### ISSUE TITLE
Changing bacticks to (double) quotes

### ISSUE THREAD

**Issue by kristijanhusak** [axelvc/template-string.nvim#1]
Hi,

Are there any plans to support converting bacticks to quotes when user deletes a variable? I noticed in the gif (see below) from vscode plugin that it has the option to go both ways. Would be great to have both.

![gif](https://raw.githubusercontent.com/meganrogge/template-string-converter/master/src/images/auto-remove.gif)

Very nice and simple plugin btw, very useful.

**Comment by axelvc** [comment]
Yeah, I'd like to implement this feature, but I need to think more about how to implement it to avoid problems like these: meganrogge/template-string-converter#43

**Comment by kristijanhusak** [comment]
Wasn't aware of those issues. I think there should still be a branch that has it implemented as simple as possible, and have people test it out. Most probably it will not have some of those issues vscode plugin has, but also some other issues might arise.

**Comment by axelvc** [comment]
I've implemented this feature (disabled by default). You can test and report any issues you find 🙂

#2

**Comment by kristijanhusak** [comment]
Awesome, thanks!

**Comment by camiloaromero23** [comment]
@axelvc I tried using the feature but cant manage to make it work. Can you give me a simple explanation or add it to the README? Appreciate a lot your effort 💪🏼

**Comment by camiloaromero23** [comment]
I made it work by deleting the character with `x` under normal mode. Is it the way its supposed to be working?

**Comment by axelvc** [comment]
> Can you give me a simple explanation or add it to the README?

You need to enable the option in the setup function. That should be enough

```lua
require('template-string').setup {
  remove_template_string = true,
}
```

> I made it work by deleting the character with `x` under normal mode. Is it the way its supposed to be working?

The feature should work in **Normal** and **Insert** mode, but there are some cases where the plugin doesn't remove the backticks. You can see them here: https://github.com/axelvc/template-string.nvim/pull/4#issue-1342876268

If you've found a new issue, feel free to report it by opening an issue.
