### ISSUE TITLE
Python "before_quotes"  incorrectly triggers on multiline strings

### ISSUE THREAD

**Issue by barrettruth** [axelvc/template-string.nvim#11]
Attempting to type out the following python string which ought to be converted to a format string:

```python
a = """
{hi}
"""
```

does not work. This is because "before_quotes" function checks the vertical position of the cursor before any special multiline string handling is done, and no "f" is inserted. The same happens when trying to delete the interpolation, and any "f" in the string remains.

**Comment by axelvc** [comment]
It should work fine now. Thanks!
