### ISSUE TITLE
add support for vue?

### ISSUE THREAD

**Issue by ilyaliao** [axelvc/template-string.nvim#14]
As stated in the title, using Vue is quite similar to using JavaScript and JavaScriptReact. Is there a possibility for Vue to be supported in the future?

![截圖 2023-08-24 下午10 16 10](https://github.com/axelvc/template-string.nvim/assets/93901409/b6489530-d572-4d9c-b6d7-1a827481767b)

**Comment by axelvc** [comment]
Adding `vue` to the config should be enough to make it work.

```lua
require('template-string').setup({
  filetypes = { 'vue', 'html', 'typescript', 'javascript', 'typescriptreact', 'javascriptreact', 'python' },
})
```
I'll add this to the default config, meanwhile you can add it manually
