### ISSUE TITLE
Feedback and suggestions on remove template string option

### ISSUE THREAD

**Issue by kristijanhusak** [axelvc/template-string.nvim#3]
Hey,

I gave new `remove_template_string` option a try, and as you properly assumed, there are some bugs with it. Here are few that I found:

1. starting template string and then typing something in it removes the backticks. Vscode has the same issue.
2. Deleting a variable inside the template string from normal mode via motion (example: `da{`, or doing `x` while on `}`), doesn't register the change.

For the first issue, a solution is just to ignore the template strings that were started empty. Of course that sounds simpler than it really is. There's no a simple way to track what was started as empty template string. 
My idea is to use [nvim_buf_set_extmark](https://neovim.io/doc/user/api.html#nvim_buf_set_extmark()) when string node is found and attach the extmark to it. That way you will get some identifier by which you can track specific nodes, and then properly ignore it. This is just a theory, I'm not sure if it will work out.

Second issue seems to be solved when additionally "TextChanged" event is added additionally to "TextChangedI".

```diff
diff --git a/lua/template-string/init.lua b/lua/template-string/init.lua
index 7953f23..fc44853 100644
--- a/lua/template-string/init.lua
+++ b/lua/template-string/init.lua
@@ -37,7 +37,7 @@ function M.setup(options)
 				return
 			end
 
-			autocmd("TextChangedI", {
+			autocmd({ "TextChanged", "TextChangedI" }, {
 				group = M.group,
 				buffer = ev.buf,
 				callback = M.handle_type,
```

Hope this helps.

**Comment by axelvc** [comment]
Thanks for your suggestions. I didn't know about the extmarks

They should be fixed now

**Comment by kristijanhusak** [comment]
Everything seems to be working now, thanks!
Your solution is much simpler and it works.
