### ISSUE TITLE
Bug: erroneous insertion of Python template string 

### ISSUE THREAD

**Issue by barrettruth** [axelvc/template-string.nvim#8]
When typing inside of the following python string:
```python
x = """
{0}, {1}, and {0}
"""
```
template-strings erroneously converts the string into an f-string. As you know, this is because you can have a number inside the braces (say *i*) to signify the ith parameter passed to the string - the numbers 0, 1, and 0 are not actually literals desired to be directly interpolated into the string.

For the solution, with python filetypes I believe if you checked for the first char of the text inside the "{}" in a python string (if that's possible with treesitter in this case) to be a number that would be sufficient (if the first char is a number, don't prepend an "f" to the string - otherwise do.

Generally there's a lot of special cases for the .format() method of python strings - which probably involves some deeper thinking about what strings are valid in python in which you can be certain the coder wants a template string inserted. In Java/TypeScript the solution is very simple, but it's not quite the same (I think?) with Python.

**Comment by barrettruth** [comment]
Also, we can solve this by ignoring anything other than variables (which start with an underscore or letter in python) in interpolation strings using something like this (though I'm unsure if it addresses nested interpolations:

```lua
      or text:match("{[^_%a].*}")
```

as a condition to handle_quote_string [here](https://github.com/axelvc/template-string.nvim/blob/e347d83c80bd1ec77e13a37962013199d216a8cd/lua/template-string/langs/python.lua#L73)

**Comment by barrettruth** [comment]
@axelvc python f-strings seem to be too complicated to actually correctly detect without a python parsing library. As such I'll just go ahead and close this issue. However I do still think #11 should be resolved.

**Comment by axelvc** [comment]
As you said, this could be prone to lots of errors. I'd like to look into this more before implement something.

> Also, we can solve this by ignoring anything other than variables (which start with an underscore or letter in python) in interpolation strings using something like this (though I'm unsure if it addresses nested interpolations:

That sounds good to me. Did you find any trouble with that?

**Comment by barrettruth** [comment]
@axelvc That solution does work, but as I said, not for all cases (since almost anything can be inside of the interpolation brackets).

Right now I just inserted these conditions into handle_quote_string in python.lua:

```lua
      or text:match("{%d+}")
      or text:match("{[^_%a].*}")
```

It's not perfect, which is why I don't know if you should add that code.
